---
title: "visualization"
author: "Chuhan Yue"
date: "2023-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(purrr)
```

```{r}
customerdata<-read.csv("ab_data.csv")
summary(customerdata)
```

```{r}
#删掉group和page不一样的数据
```

the converted rate are similiar in the group "control" and the group "treatment".
```{r}
#group converted
freq_table <- table(customerdata[,3],customerdata[,5])
result_df <- as.data.frame.matrix(freq_table)
ggplot(data = result_df, aes(x = rownames(result_df), y = result_df[,1])) +
  geom_bar(stat = 'identity', position = 'dodge2', fill = 'lightblue') +
  geom_bar(stat = 'identity', aes(y = result_df[,2]),  position = 'dodge2',fill = 'lightgreen') +
  labs(title = 'Count of a and b for 0 and 1') +
  xlab('Values (a and b)') +
  ylab('Count')
```
the converted rate are similiar in the old page and the new page.
```{r}
#page converted
freq_table1 <- table(customerdata[,4],customerdata[,5])
result_df1 <- as.data.frame.matrix(freq_table1)
ggplot(data = result_df1, aes(x = rownames(result_df1), y = result_df1[,1])) +
  geom_bar(stat = 'identity', position = 'dodge2', fill = 'lightblue') +
  geom_bar(stat = 'identity', aes(y = result_df1[,2]),  position = 'dodge2',fill = 'lightgreen') +
  labs(title = 'Count of a and b for 0 and 1') +
  xlab('Values (a and b)') +
  ylab('Count')
```
date did not have relationship with converted
```{r}
#timestamp converted
customerdata$day<-substr(customerdata[,2],9,10)%>%as.numeric()
freq_table2 <- table(customerdata[,8],customerdata[,5])
result_df2 <- as.data.frame.matrix(freq_table2)
result_df2$percent<-result_df2[,2]/ result_df2[,1]
ggplot(data = result_df2, aes(x = rownames(result_df2), y = result_df2[,1])) +
  geom_bar(stat = 'identity', position = 'dodge2', fill = 'lightblue') +
  geom_bar(stat = 'identity', aes(y = result_df2[,2]),  position = 'dodge2',fill = 'lightgreen') +
  labs(title = 'Count of a and b for 0 and 1') +
  xlab('Values (a and b)') +
  ylab('Count')
```

```{r}
has_duplicates <- any(duplicated(customerdata[,1]))
frequency_table <- table(customerdata[,1])
duplicates <- names(frequency_table[frequency_table > 1])
```