---
title: "Data Explore for task 4,5"
author: "Yang Lyu"
date: "16/10/2023"
output: pdf_document
---
```{r}
library(dplyr)
```

```{r}
mimic3d <- read.csv("mimic3d.csv", header = TRUE)
mimic3d_clean <- na.omit(subset(mimic3d,select = -marital_status))
```

```{r}
cat("\n*Group by gender:")
table(mimic3d_clean$gender)
cat("\n*Group by admit_type:")
table(mimic3d_clean$admit_type)
cat("\n*Group by admit_location:")
table(mimic3d_clean$admit_location)
cat("\n*Group by insurance")
table(mimic3d_clean$insurance)
cat("\n*Group by ethnicity")
table(mimic3d_clean$ethnicity)
cat("\n*Group by religion")
table(mimic3d_clean$religion)
cat("\n*Group by ethnicity")
table(mimic3d$ethnicity)
```

```{R}
# Pick cate data and valued them
cate_data <- mimic3d_clean %>% transmute(
  LOSdays_Less2 = ifelse(LOSdays <= 2, 1, 0), 
  gender = as.numeric(factor(gender, levels = c("F", "M"), labels = c(0, 1))), 
  admit_type = as.numeric(factor(admit_type, levels = c("ELECTIVE","EMERGENCY","NEWBORN","URGENT"), labels = c(0,1,2,3))),
  insurance = as.numeric(factor(insurance, levels = c("Government","Medicaid","Medicare","Private","Self Pay"), labels = c(0,1,2,3,4))
  ))
cate_data <- cbind(cate_data, mimic3d_clean$ExpiredHospital, mimic3d_clean$LOSgroupNum)
View(cate_data)
```

```{r}
#create a list contain pairwise comparsion between cate variables and LOSdays_less2
# create df1 containing  column 1  and column 2, put df1 into first place in a list 
# create df2 containing column 1 and column 3, put df2 into 2nd of the list, 
# create df3 containing column 1 and 4, put df3 into 3rd of the list, 
# create df4 containing  column 1  and 5, put df4 into 4th in list, 
# create df5 containing column 1 and 6, put df5 into 5rd of the list.
create_list <- function(df) {
  # Create an empty list
  my_list <- list()
  # Create and populate data frames and add them to the list
  for (i in 2:6) {
    df_name <- paste0("df", i - 1)
    new_df <- data.frame(df[, 1], df[, i])
    my_list[[df_name]] <- new_df
  }
  return(my_list)
}
create_list(cate_data)

```

```{r}
chi_square_test <- function(list, index){
  my_df <- create_list(cate_data)[[index]]
  chi_square_table <- table(my_df)
  chi_square_result <- chisq.test(chi_square_table)
  return(chi_square_result)
}
chi_square_test(create_list(cate_data), 1)
cat("*Chi square test on LOSdays and gender has p_value 0.01364")
chi_square_test(create_list(cate_data), 2)
cat("*Chi square test on LOSdays and  admit_type has p_value <2.2*10^-16")
chi_square_test(create_list(cate_data), 3)
cat("*Chi square test on LOSdays and  insurance has p_value <2.2*10^-16")
chi_square_test(create_list(cate_data), 4)
cat("*Chi square test on LOSdays and  ExpiredHospital has p_value <2.2*10^-16")
chi_square_test(create_list(cate_data), 5)
cat("*Chi square test on LOSdays and LOSgroupNum has p_value <2.2*10^-16")
```