---
title: "Untitled"
author: 
  - Teng Li(7373086)
  - Shiya Gao(300381032) 
  - Chuhan Yue(300376046)
  - Yang Lyu(8701121)
output: 
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex
fontsize: 11pt
header-includes: 
  - \renewcommand{\and}{\\}
  - \usepackage{float}
  - \floatplacement{figure}{H}
bibliography: References.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(plotly)
library(tidyverse)
```

```{r}
# Test Case
old_distinct<-data.frame(Id=1:1000, converted=rbinom(1000, 1, 0.52))
new_distinct<-data.frame(Id=1:1000, converted=rbinom(1000, 1, 0.483))

my_instance <- MyClass$new(old_distinct=old_distinct, new_distinct=new_distinct,rows_per_subset = 10,
                           alpha_prior_old=1,
                           alpha_prior_new=1,
                           beta_prior_old=1,
                           beta_prior_new=1)

frame<-my_instance$calculateMean()

ggplot(frame, aes(x = size, y = value)) +
  geom_point(shape = 16, color = "blue") +
  labs(title = "Scatter Plot Example", x = "X-axis Label", y = "Y-axis Label")

my_instance$PlotCI()
```

```{r}
data <- read.csv("ab_data.csv")
mimic3d <- read.csv("mimic3d.csv")

#cleaning data
old <- data %>% filter(landing_page == "old_page" & group == "control")
new <- data %>% filter(landing_page == "new_page" & group == "treatment")
old_distinct <- old %>% distinct(old$user_id, .keep_all = TRUE)
new_distinct <- new %>% distinct(new$user_id, .keep_all = TRUE)
```

```{r}
#using non-informative priors
my_instance <- MyClass$new(old_distinct,new_distinct,rows_per_subset = 1000,
                           alpha_prior_old=1,
                           alpha_prior_new=1,
                           beta_prior_old=1,
                           beta_prior_new=1)

frame0<-my_instance$calculateMean()


ggplot(frame0, aes(x = size, y = value)) +
  geom_point(shape = 16, color = "blue") +
  labs(title = "Scatter Plot Example", x = "X-axis Label", y = "Y-axis Label")

```

```{r}
#using informative priors, subset size = 100
my_instance <- MyClass$new(old_distinct,new_distinct,rows_per_subset = 100,
                           alpha_prior_old=2,
                           alpha_prior_new=2,
                           beta_prior_old=20,
                           beta_prior_new=20)

frame1<-my_instance$calculateMean()


ggplot(frame1, aes(x = size, y = value)) +
  geom_point(shape = 16, color = "blue") +
  labs(title = "Scatter Plot Example", x = "X-axis Label", y = "Y-axis Label")
```

```{r}
#Mean_old & Mean_new Plot

result_mean <- frame1[, -which(names(frame1) == "value")]

#reorganize into long format
result_long1 <- gather(result_mean, key = "Variable", value = "Mean", posterior_old_mean:posterior_new_mean)

ggplot(result_long1, aes(x = size, y = Mean, color = Variable)) +
  geom_line() +
  labs(title = "Mean Comparison",
       x = "Size",
       y = "Mean") +
  scale_color_manual(values = c("posterior_old_mean" = "blue", "posterior_new_mean" = "red"))
```

```{r}
my_instance$PlotCI()
```